fmu_file: boiler_cdl/Buildings_Controls_OBC_ASHRAE_PrimarySystem_BoilerPlant_SetPoints_HotWaterSupplyTemperatureReset.fmu
model_update_rate: 300
web_api_port: 5000
brick_file: dbc_brick_expanded.ttl
bacnet_init_file: bacnet_and_data/BACnet_init_temp_reset.ini

